#!/usr/bin/env bash
if which getent >/dev/null; then
	REALNAME=$(getent passwd $USER|awk -F : '{print $5}' | awk -F , '{print $1}')
else
	REALNAME=$(grep $USER /etc/passwd|awk -F : '{print $5}' | awk -F , '{print $1}')
fi

FILENAME=$(basename $1)
FILE=$(echo $FILENAME | sed 's/\(.*\)\..*/\1/' | sed 's/[._]/ /g')

sed "s/%%AUTHOR%%/$REALNAME/g;s/%%FILE%%/$FILE/g"
